### PR TITLE
Earcanal 3.x/features

### PR DESCRIPTION
**Pull request by vsoch**
@earcanal this PR we will use to continue working on the updates to this package! I've made some changes to get us started, and when you have the bandwidth you can give a shot at looking at (the actual) tests. Likely the bugs are what were there before.

### CODE REVIEW

**Comment by vsoch** [comment]
Wow almost perfect first shot! The only things I see are:

```
* checking R code for possible problems ... NOTE
process_ant: no visible global function definition for ‘data_frame’
process_ant: no visible global function definition for ‘%>%’
process_ant: no visible global function definition for ‘filter’
process_ant: no visible binding for global variable ‘exp_stage’
process_ant: no visible binding for global variable ‘trial_type’
process_ant: no visible binding for global variable ‘correct_response’
process_ant: no visible global function definition for ‘select’
process_ant: no visible binding for global variable ‘trial_id’
process_ant: no visible binding for global variable ‘trial_index’
process_ant: no visible binding for global variable ‘internal_node_id’
process_ant: no visible binding for global variable ‘text’
process_ant: no visible binding for global variable ‘timing_post_trial’
process_ant: no visible binding for global variable ‘view_history’
process_ant: no visible binding for global variable ‘stimulus’
process_ant: no visible binding for global variable ‘time_elapsed’
process_ant: no visible global function definition for ‘mutate’
Undefined global functions or variables:
  %>% correct_response data_frame exp_stage filter internal_node_id
  mutate select stimulus text time_elapsed timing_post_trial trial_id
  trial_index trial_type view_history
Consider adding
  importFrom("graphics", "text")
  importFrom("stats", "filter")
```
@earcanal

**Comment by earcanal** [comment]
I'd like to keep the package named `attentionnetworktest` rather than `attentionnetworktask` (see rename in 16e18a8c8b) as that's what it's called in the literature.  Given that, I'm not sure of the best way to do the merge of the final bits from #1 into #2 (i.e. I'm nearing the limits of my git-fu!).  Actually, I think I've done a lot of the same work as you in c1d4160af3ff668, so you can probably just revert 16e18a8c8b to lose the renaming.  If you do that then push `Earcanal 3.x/features`, I can merge with #1 and PR.

Once done, I think we're good.

**Comment by vsoch** [comment]
We need to decide on a naming scheme and stick with It.

**Comment by earcanal** [comment]
I'm proposing `attentionnetworktest` as It's called the Attention Network Test extensively in the literature, notably by the people who created it (Fan et al., 2002).

**Comment by vsoch** [comment]
Then why is this PR to "attention-network-task" ?

**Comment by vsoch** [comment]
Please move work to here, this is a different task, closing. https://github.com/expfactory-experiments/attention-network-test/pull/1

**Pull request closed without merging**
